pub mod function;

/// The composite used as input for this function.
// Importing the types generated by kopium and opting-in to the default implementations
// for the resource mapping traits from the sdk.
pub mod composite_resource {
    use crossplane_rust_sdk_unofficial::{TryFromResource, TryIntoResource};

    include!("generated/xrd.rs");

    impl TryFromResource for Config {}
    impl TryIntoResource for Config {}
}
