use crate::function::ExampleFunction;
use crossplane_rust_sdk_unofficial::server::run_server;
use crossplane_rust_sdk_unofficial::tokio;

pub mod function;

/// The composite used as input for this function.
// Importing the types generated by kopium and opting-in to the default implementations
// for the resource mapping traits from the sdk.
pub mod composite_resource {
    use crossplane_rust_sdk_unofficial::TryFromResource;

    include!("generated/xrd.rs");
    impl TryFromResource for Config {}
}

#[tokio::main]
/// Starts the grpc server and handles sigterm/sigint for shutdown
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    run_server(ExampleFunction {}).await?;
    Ok(())
}
